### PR TITLE
#160819084 Ft order history to develop

### PR DESCRIPTION
**Pull request by Kasulejoseph**
**What this PR do?**
 -  Add order history and menu end points 
**Description of tasks to be completed***
 - A user should be able to add to view all the his previous orders
given he browser the end point `/api/v1/orders`.
- The PR also add a functionality of the admin to add `GET /api/v1/menu` a menu and 
users to view all the posted menu `POST /api/v1/menu`
-**How to manually test**
- Log in as a user in postman
- Browse the route `localhost:5000/api/v1/orders` and your previous orders will be
displayed in case you have
*To add menu*
- Login as an admin, insert menu fields and post
*To see menu*
- you create a get request on `/api/v1/menu`
**Relevant Stories**
#160822749
#160819084

**Screenshots**
1. order history
orderhist

2. menu
onmenu

### CODE REVIEW

**Comment by MuhweziDeo** [comment]
what desc mean

**Comment by kafuuma** [comment]
I see you are implementing OOP
very good

U can also include a screenshot of your tests running in the PR file

**Comment by Kasulejoseph** [comment]
> what does desc mean

description

**Comment by Sebuliba-Adrian** [comment]
Resolve merge conflicts commit

**Comment by Kasulejoseph** [comment]
I have Rectified everything

**Pull request merged**
